int CHORD_C[] = {0, NOTE_C3, NOTE_E3, NOTE_G3, NOTE_C4, NOTE_E4};
int CHORD_C7[] = {0, NOTE_C3, NOTE_E3, NOTE_Bb3, NOTE_C4, NOTE_E4};
int CHORD_Cm[] = {0, NOTE_C3, NOTE_G3, NOTE_C4, NOTE_Eb4, NOTE_G4};
int CHORD_Cmaj7[] = {0, NOTE_C3, NOTE_E3, NOTE_B3, NOTE_C4, NOTE_E4};
int CHORD_Cm6_Eb[] = {NOTE_Eb2, NOTE_A2, NOTE_Eb3, NOTE_G3, NOTE_C4, 0};

int CHORD_Db[] = {0, 0, NOTE_Db3, NOTE_Ab3, NOTE_Db4, NOTE_F4};
int CHORD_Dbm[] = {0, 0, NOTE_Db3, NOTE_Ab3, NOTE_Db4, NOTE_E4};
int CHORD_Dbm6[] = {NOTE_E2, NOTE_Bb2, 0, NOTE_Ab3, NOTE_Db4, NOTE_E4}; //*

int CHORD_D[] = {0, 0, NOTE_D3, NOTE_A3, NOTE_D4, NOTE_FS4};
int CHORD_D7[] = {0, 0, NOTE_D3, NOTE_A3, NOTE_B3, NOTE_FS4};
int CHORD_Dm[] = {0, 0, NOTE_D3, NOTE_A3, NOTE_D4, NOTE_F4};
int CHORD_D7add13[] = {0, NOTE_D3, NOTE_FS3, NOTE_C4, NOTE_D4, NOTE_B4};
int CHORD_Ddim[] = {NOTE_F2, 0, NOTE_D3, NOTE_GS3, NOTE_B3, 0}; //*

int CHORD_Eb7[] = {0, NOTE_Eb3, NOTE_G3, NOTE_Bb3, NOTE_Db4, NOTE_G4}; //*
int CHORD_Eb7s5[] = {0, 0, NOTE_G3, NOTE_Db4, NOTE_Eb3, NOTE_B4}; //*

int CHORD_E[] =  {NOTE_E2, NOTE_B2, NOTE_E3, NOTE_GS3, NOTE_B3, NOTE_E4};
int CHORD_E7[] = {NOTE_E2, NOTE_B2, NOTE_E3, NOTE_GS3, NOTE_D4, NOTE_E4};
int CHORD_Em[] = {0, 0, NOTE_E3, NOTE_G3, NOTE_B3, NOTE_E4};
int CHORD_EmD[] = {0, 0, NOTE_D3, NOTE_G3, NOTE_B3, NOTE_E4};
int CHORD_EmC[] = {0, 0, NOTE_C3, NOTE_G3, NOTE_B3, NOTE_E4};
int CHORD_EmB[] = {0, 0, NOTE_B2, NOTE_G3, NOTE_B3, NOTE_E4};
int CHORD_Em7[] = {NOTE_E2, NOTE_B2, NOTE_E3, NOTE_G3, NOTE_D4, NOTE_E4};

int CHORD_F[] = {NOTE_F2, NOTE_C3, NOTE_F3, NOTE_A3, NOTE_C4, NOTE_F4};
int CHORD_F7[] = {NOTE_F2, NOTE_C3, NOTE_F3, NOTE_A3, NOTE_Eb4, NOTE_F4};
int CHORD_Fm[] = {NOTE_F2, NOTE_C3, NOTE_F3, NOTE_Ab3, NOTE_C4, NOTE_F4};
int CHORD_Fm7[] = {NOTE_F2, 0, NOTE_Eb3, NOTE_Ab3, NOTE_C4, 0}; //*
int CHORD_F7s5[] = {0, NOTE_A2, NOTE_DS3, NOTE_A3, NOTE_CS4, NOTE_F4}; //*

int CHORD_Gb[] = {NOTE_Gb2, NOTE_Db3, NOTE_Gb3, NOTE_Bb3, NOTE_Db4, NOTE_Gb4};
int CHORD_Gbm[] = {NOTE_Gb2, NOTE_Db3, NOTE_Gb3, NOTE_A3, NOTE_Db4, NOTE_Gb4};

int CHORD_G[] = {NOTE_G2, NOTE_B2, NOTE_D3, NOTE_G3, NOTE_B3, NOTE_G4};
int CHORD_G7[] = {NOTE_G2, NOTE_B2, NOTE_D3, NOTE_G3, NOTE_B3, NOTE_F4};
int CHORD_Gm[] = {NOTE_G2, NOTE_D3, NOTE_G3, NOTE_Bb3, NOTE_D4, NOTE_G4};
int CHORD_Gm7[] = {NOTE_G2, NOTE_D3, NOTE_F3, NOTE_Bb3, NOTE_F4, NOTE_G4};

int CHORD_Ab[] = {NOTE_Ab2, NOTE_C3, NOTE_Eb3, NOTE_Ab3, NOTE_C4, 0}; //*
int CHORD_Abm[] = {NOTE_Ab2, NOTE_Eb3, NOTE_Ab3, NOTE_B3, NOTE_Eb4, NOTE_Ab4};

int CHORD_A[] = {0, NOTE_A2, NOTE_E3, NOTE_A3, NOTE_CS4, NOTE_E4};
int CHORD_A7[] = {0, NOTE_A2, NOTE_E3, NOTE_G3, NOTE_CS4, NOTE_E4};
int CHORD_Am[] = {0, NOTE_A2, NOTE_E3, NOTE_A3, NOTE_C4, NOTE_E4};
int CHORD_Am9[] = {NOTE_A2, NOTE_E3, NOTE_G3, NOTE_C4, NOTE_E4, NOTE_B4};
int CHORD_Am7b5_D[] = {0, NOTE_D3, NOTE_A3, NOTE_Eb4, NOTE_G4, NOTE_C5};

int CHORD_Bbm7[] = {0, NOTE_Bb2, 0, NOTE_Ab3, NOTE_Db4, NOTE_F4}; //*
int CHORD_Bb7[] = {0, NOTE_Bb2, NOTE_F3, NOTE_Ab3, NOTE_D4, NOTE_F4};

int CHORD_B[] = {0, NOTE_B2, NOTE_FS3, NOTE_B3, NOTE_DS3, NOTE_FS4};
int CHORD_B7[] = {0, NOTE_B2, NOTE_DS3, NOTE_A3, NOTE_B3, NOTE_FS4};
int CHORD_Bm[] = {0, NOTE_B2, NOTE_FS3, NOTE_B3, NOTE_D3, NOTE_FS4};

int DRUM_BASS[] = {36, 0, 0, 0, 0, 0};
int DRUM_SIDE[] = {37, 0, 0, 0, 0, 0};
int CYM_1[] = {51, 0, 0, 0, 0, 0};
int CYM_2[] = {49, 0, 0, 0, 0, 0};
int BELLS[] = {83, 0, 0, 0, 0, 0};
